a = {
    'input_modalities':
    'default',
    'no_data_parallelism':
    False,
    'symbol_modality_skip_top':
    False,
    'daisy_chain_variables':
    True,
    'scheduled_sampling_prob':
    0.0,
    'layer_prepostprocess_dropout':
    0.1,
    'use_pad_remover':
    True,
    'hidden_size':
    256,
    'learning_rate_decay_rate':
    1.0,
    'learning_rate_decay_steps':
    5000,
    'grad_noise_scale':
    0.0,
    'min_length':
    0,
    'problem_choice':
    'adaptive',
    'optimizer_adafactor_memory_exponent':
    0.8,
    'parameter_attention_value_channels':
    0,
    'compress_steps':
    0,
    'shared_embedding_and_softmax_weights':
    True,
    'summarize_grads':
    False,
    'activation_dtype':
    'float32',
    'eval_steps':
    100,
    'optimizer_adafactor_beta1':
    0.0,
    'max_target_seq_length':
    0,
    'sampling_temp':
    1.0,
    'learning_rate':
    0.2,
    'eval_run_autoregressive':
    False,
    'optimizer_adam_beta2':
    0.997,
    'summarize_vars':
    False,
    'kernel_width':
    1,
    'optimizer_adafactor_multiply_by_parameter_scale':
    True,
    'factored_logits':
    False,
    'sampling_method':
    'argmax',
    'initializer_gain':
    1.0,
    'optimizer_adam_epsilon':
    1e-09,
    'moe_hidden_sizes':
    '2048',
    'layer_preprocess_sequence':
    'n',
    'max_length':
    256,
    'num_hidden_layers':
    2,
    'num_decoder_layers':
    0,
    'relu_dropout_broadcast_dims':
    '',
    'learning_rate_cosine_cycle_steps':
    250000,
    'layer_postprocess_sequence':
    'da',
    'learning_rate_decay_staircase':
    False,
    'prepend_mode':
    'none',
    'optimizer_adafactor_factored':
    True,
    'optimizer_adafactor_clipping_threshold':
    1.0,
    'initializer':
    'uniform_unit_scaling',
    'weight_noise':
    0.0,
    'kernel_height':
    3,
    'target_modality':
    'default',
    'eval_drop_long_sequences':
    False,
    'length_bucket_step':
    1.1,
    'multiply_embedding_mode':
    'sqrt_depth',
    'proximity_bias':
    False,
    'moe_loss_coef':
    0.01,
    'symbol_dropout':
    0.0,
    'optimizer_momentum_momentum':
    0.9,
    'clip_grad_norm':
    0.0,
    'learning_rate_schedule':
    'constant*linear_warmup*rsqrt_decay*rsqrt_hidden_size',
    'optimizer':
    'Adam',
    'max_input_seq_length':
    0,
    'self_attention_type':
    'dot_product',
    'pos':
    'timing',
    'moe_k':
    2,
    'filter_size':
    1024,
    'attention_dropout':
    0.1,
    'optimizer_adafactor_decay_type':
    'pow',
    'scheduled_sampling_gold_mixin_prob':
    0.5,
    'optimizer_adam_beta1':
    0.9,
    'norm_epsilon':
    1e-06,
    'label_smoothing':
    0.1,
    'weight_decay':
    0.0,
    'relu_dropout':
    0.1,
    'scheduled_sampling_warmup_steps':
    50000,
    'learning_rate_minimum':
    None,
    'ffn_layer':
    'dense_relu_dense',
    'max_relative_position':
    0,
    'learning_rate_constant':
    2.0,
    'attention_dropout_broadcast_dims':
    '',
    'data_dir':
    '/home/chli4934/ptb/t2t_data',
    'attention_key_channels':
    0,
    'symbol_modality_num_shards':
    16,
    'moe_num_experts':
    64,
    'layer_prepostprocess_dropout_broadcast_dims':
    '',
    'learning_rate_warmup_steps':
    8000,
    'nbr_decoder_problems':
    1,
    'learning_rate_decay_scheme':
    'noam',
    'train_steps':
    250000,
    'split_to_length':
    0,
    'num_encoder_layers':
    0,
    'norm_type':
    'layer',
    'optimizer_momentum_nesterov':
    False,
    'parameter_attention_key_channels':
    0,
    'min_length_bucket':
    8,
    'dropout':
    0.2,
    'use_fixed_batch_size':
    False,
    'batch_size':
    4096,
    'optimizer_adafactor_beta2':
    0.999,
    'num_heads':
    4,
    'force_full_predict':
    False,
    'model_dir':
    '/home/chli4934/ptb/t2t_train/languagemodel_ptb10k/transformer-transformer_small',
    'attention_value_channels':
    0
}

b = {
    'input_modalities':
    'default',
    'no_data_parallelism':
    False,
    'symbol_modality_skip_top':
    False,
    'daisy_chain_variables':
    True,
    'scheduled_sampling_prob':
    0.0,
    'layer_prepostprocess_dropout':
    0.1,
    'use_pad_remover':
    True,
    'hidden_size':
    256,
    'learning_rate_decay_rate':
    1.0,
    'learning_rate_decay_steps':
    5000,
    'grad_noise_scale':
    0.0,
    'min_length':
    0,
    'problem_choice':
    'adaptive',
    'optimizer_adafactor_memory_exponent':
    0.8,
    'parameter_attention_value_channels':
    0,
    'compress_steps':
    0,
    'shared_embedding_and_softmax_weights':
    True,
    'summarize_grads':
    False,
    'activation_dtype':
    'float32',
    'eval_steps':
    100,
    'optimizer_adafactor_beta1':
    0.0,
    'max_target_seq_length':
    0,
    'sampling_temp':
    1.0,
    'learning_rate':
    0.2,
    'eval_run_autoregressive':
    False,
    'optimizer_adam_beta2':
    0.997,
    'summarize_vars':
    False,
    'kernel_width':
    1,
    'optimizer_adafactor_multiply_by_parameter_scale':
    True,
    'factored_logits':
    False,
    'sampling_method':
    'argmax',
    'initializer_gain':
    1.0,
    'optimizer_adam_epsilon':
    1e-09,
    'moe_hidden_sizes':
    '2048',
    'layer_preprocess_sequence':
    'n',
    'max_length':
    256,
    'num_hidden_layers':
    2,
    'num_decoder_layers':
    0,
    'relu_dropout_broadcast_dims':
    '',
    'learning_rate_cosine_cycle_steps':
    250000,
    'layer_postprocess_sequence':
    'da',
    'learning_rate_decay_staircase':
    False,
    'prepend_mode':
    'none',
    'optimizer_adafactor_factored':
    True,
    'optimizer_adafactor_clipping_threshold':
    1.0,
    'initializer':
    'uniform_unit_scaling',
    'weight_noise':
    0.0,
    'kernel_height':
    3,
    'target_modality':
    'default',
    'eval_drop_long_sequences':
    False,
    'length_bucket_step':
    1.1,
    'multiply_embedding_mode':
    'sqrt_depth',
    'proximity_bias':
    False,
    'moe_loss_coef':
    0.01,
    'symbol_dropout':
    0.0,
    'optimizer_momentum_momentum':
    0.9,
    'clip_grad_norm':
    0.0,
    'learning_rate_schedule':
    'constant*linear_warmup*rsqrt_decay*rsqrt_hidden_size',
    'optimizer':
    'Adam',
    'max_input_seq_length':
    0,
    'self_attention_type':
    'dot_product',
    'pos':
    'timing',
    'moe_k':
    2,
    'filter_size':
    1024,
    'attention_dropout':
    0.1,
    'optimizer_adafactor_decay_type':
    'pow',
    'scheduled_sampling_gold_mixin_prob':
    0.5,
    'optimizer_adam_beta1':
    0.9,
    'norm_epsilon':
    1e-06,
    'label_smoothing':
    0.1,
    'weight_decay':
    0.0,
    'relu_dropout':
    0.1,
    'scheduled_sampling_warmup_steps':
    50000,
    'learning_rate_minimum':
    None,
    'ffn_layer':
    'dense_relu_dense',
    'max_relative_position':
    0,
    'learning_rate_constant':
    2.0,
    'attention_dropout_broadcast_dims':
    '',
    'data_dir':
    '/home/chli4934/ptb/t2t_data',
    'attention_key_channels':
    0,
    'symbol_modality_num_shards':
    16,
    'moe_num_experts':
    64,
    'layer_prepostprocess_dropout_broadcast_dims':
    '',
    'learning_rate_warmup_steps':
    8000,
    'nbr_decoder_problems':
    1,
    'learning_rate_decay_scheme':
    'noam',
    'train_steps':
    250000,
    'split_to_length':
    0,
    'num_encoder_layers':
    0,
    'norm_type':
    'layer',
    'optimizer_momentum_nesterov':
    False,
    'parameter_attention_key_channels':
    0,
    'min_length_bucket':
    8,
    'dropout':
    0.2,
    'use_fixed_batch_size':
    False,
    'batch_size':
    4096,
    'optimizer_adafactor_beta2':
    0.999,
    'num_heads':
    4,
    'force_full_predict':
    False,
    'model_dir':
    '/home/chli4934/ptb/t2t_train/languagemodel_ptb10k/transformer-transformer_small',
    'attention_value_channels':
    0
}
